language: java
jdk:
  - openjdk8
before_install: # lets update the very old version of ANT in TravisCI
  - wget --no-check-certificate http://repository.microej.com/p2/sdk/plugins/com.is2t.eclipse.plugin.easyant4e_1.7.4.20200309-1134.jar
  - wget --no-check-certificate http://repository.microej.com/p2/sdk/plugins/com.is2t.eclipse.plugin.easyant4e.offlinerepo_1.6.0.20200309-1134.jar
  - wget --no-check-certificate https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip
  - unzip -o com.is2t.eclipse.plugin.easyant4e.offlinerepo_1.6.0.20200309-1134.jar
  - unzip -o ./repositories/microej-build-repository.zip -d repositories
  - unzip -o com.is2t.eclipse.plugin.easyant4e_1.7.4.20200309-1134.jar
  - unzip -o apache-ant-1.9.9-bin.zip
  - cp -r ./apache-ant-1.9.9/bin .
  - find .
  - export PATH=$PWD/bin:$PATH
  - export MICROEJ_BUILD_REPOSITORY_DIR=$PWD/repositories
  - echo $(ant -version)
script:
  - cd test-travis-build
  - ant default
cache:
  directories:
  - $HOME/.ivy2
